name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --force

      - name: Build React app
        run: npm run build

      - name: Compress build folder
        run: tar -czf build.tar.gz build

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem
          scp -i key.pem build.tar.gz $EC2_USER@$EC2_HOST:~/build.tar.gz
          ssh -i key.pem $EC2_USER@$EC2_HOST 'bash -s' <<'EOF'
            if [ -d ~/my-app ]; then
              rm -rf ~/my-app
            fi
            tar -xzf ~/build.tar.gz -C ~/
            rm ~/build.tar.gz
            # Any additional deployment steps (e.g., restart server) go here
          EOF
